#!/bin/bash

git add .

FILE_NAMES=$(git diff --cached --name-only --diff-filter=A | sed 's/\.[^.]*$//' | paste -sd, - | sed 's/,/, /g')

if [ -z "$FILE_NAMES" ]; then
    echo "No new filenames found. Proceeding with default commit."
    git commit -m "edit"
else
    git commit -m "$FILE_NAMES"
    echo "Commit complete: $FILE_NAMES"
fi

git push origin main